sudo: required
language: generic
compiler:
- gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - avishaya@amazon.com
env:
  global:
  - AFTER_RUN_TARGET_TEST='./install_deps && ./run_integration_test.sh -v'
  - secure: 2y5QX42T1jg2lf85wmglLduddwuQTaoWk6ukzoFJ3AVoGywA4AHOgDkTvVBlQtsoxvhecoa6SJ+jnUDll9PJpGXBn06qDnAaGpI/0iheAuxoGQuR3mHs839qkMq5NfzKdfodltrNDR1XnfgUBHChj6sV0/ommYzZneQILG0PFWQb5yTO2DNtGWlP2lylHa3EGJOqkmX5CiB/f7HR7v16ak20z/q1+FjFli2dtKo72lDSHiPM0nzTLUES9bevzwOoj2iRrdXGd2TFuLu6L9JH7c0Sq9GNjZPN/pm1T7nc1/10YgAcG3cgRSOo020CqHNtPGE0NLcnhBo3A30csEZMjQrtHZSr2PR5/g9ZqHxxwbXXU3Z0lMLEUjLM8cBb0YvdZa79/lh4Gek+A+JuqlFU+L/+56KUvELUC2sHKqObOk+wGewtqKUOux8G3NROPkzOZbN1cMo3pdpFvy8BizjAYK5tgooNdY6e5hywBdf/0HXP+GnA51AtAW4nDqD+eMLO8wB61xe0ZprOn1kmZeCK8PRSCWteJXshLpVVLqFlm5lzU8c03kh/DHTW0yx4rn75GWZTCvwmCZhvARLmfcx5FB+Atqrnvca5EBHIkBITangSST0v4N7TVt0Bxk0nwdsA3pb3JJ+3ar514JVqidxA68dqtCyTrOO0xHvu7jW7nPg=
  - secure: jIrd6g0q8PV6zUJvmSBSN+OjXHPpjtr1w86foKzuHwMe2gNGX3dCJL5bw7SHvUVWoYs+37Aa14TaAA9keWNx4HhyelVFNmk1GeVgAGFVbSpoXM+anN9OuIITu59mnO3fMOIUhr+yNVJ5QJQ45QWzU182T25y2+Ao8UV3Y1MVhdOwP//XtkWL/w9LUaaiP225LLWwloJUmf7nYAuOjE/TiK9rYRTmTZXnhOS7LHeVcrx88ypaDyekLMFiXVt1eVX/77rTodlaeIVJMDS/sFj7yC/mc/6zb/zmNW7zXdcvtCT5HIHSqNZaL0WFSJYa8JXY2Joo1w1Pya8lbJq6bt2jwoFVBu4haqjP5ei8sCMPyFQ4wajKfHxzZmBqo2sXrAg7pYmN5aMy01J0DclMHAvySF9Be+b3tFt/Si9N7wqC69kgYyqEkCA5di3+n8G0WpceulFq+Cw3QGrLMS7yPENgdB3aDforDrGevUDu6RbYU/iUtNSPquhwTY7KWl0FyzLRADHHNOhLSmCii6iNQsfv6E+PjIgqub8r8btRhMPSXhKIvoyTuwO9RJtQDC6Y+jkYdsNJIhu8ss0577P5kvsWBZfR3H8H3rY9CX3LEwDQ8sRXWEKNAvu/jh71NwFCzoIbGpWC7hrR3ucF2yAClItfA1jjCJeVk+4HVON109u6/VE=
  - AWS_DEFAULT_REGION=us-west-2
  matrix:
  - ROS_DISTRO="dashing" UPSTREAM_WORKSPACE=.rosinstall
install:
- git clone -b colcon-rebase https://github.com/ipa-mdl/industrial_ci.git .ros_ci
script:
- ".ros_ci/travis.sh"
